release:
  prerelease: auto
  draft: false

env:
  # required to support multi architecture docker builds
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - CGO_ENABLED=0

builds:
  - id: linux-build
    dir: ./cmd/syft
    binary: syft
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X main.version={{.Version}}
      -X main.gitCommit={{.Commit}}
      -X main.buildDate={{.Date}}
      -X main.gitDescription={{.Summary}}

  - id: darwin-build
    dir: ./cmd/syft
    binary: syft
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    ldflags: *build-ldflags
    hooks:
      post:
        - cmd: .tool/quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
          env:
            - QUILL_LOG_FILE=/tmp/quill-{{ .Target }}.log

  - id: windows-build
    dir: ./cmd/syft
    binary: syft
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: *build-timestamp
    ldflags: *build-ldflags

archives:
  - id: linux-archives
    builds:
      - linux-build

  # note: the signing process is depending on tar.gz archives. If this format changes then .github/scripts/apple-signing/*.sh will need to be adjusted
  - id: darwin-archives
    builds:
      - darwin-build

  - id: windows-archives
    format: zip
    builds:
      - windows-build

nfpms:
  - license: "Apache 2.0"
    maintainer: "Anchore, Inc"
    homepage: &website "https://github.com/gsoc2/syft"
    description: &description "A tool that generates a Software Bill Of Materials (SBOM) from container images and filesystems"
    formats:
      - rpm
      - deb

brews:
  - tap:
      owner: anchore
      name: homebrew-syft
      token: "{{.Env.GITHUB_BREW_TOKEN}}"
    ids:
      - darwin-archives
      - linux-archives
    homepage: *website
    description: *description
    license: "Apache License 2.0"

dockers:
  - image_templates:
      - gsoc2/syft:debug
      - gsoc2/syft:{{.Tag}}-debug
      - ghcr.io/gsoc2/syft:debug
      - ghcr.io/gsoc2/syft:{{.Tag}}-debug
    goarch: amd64
    dockerfile: Dockerfile.debug
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - gsoc2/syft:debug-arm64v8
      - gsoc2/syft:{{.Tag}}-debug-arm64v8
      - ghcr.io/gsoc2/syft:debug-arm64v8
      - ghcr.io/gsoc2/syft:{{.Tag}}-debug-arm64v8
    goarch: arm64
    dockerfile: Dockerfile.debug
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - gsoc2/syft:debug-ppc64le
      - gsoc2/syft:{{.Tag}}-debug-ppc64le
      - ghcr.io/gsoc2/syft:debug-ppc64le
      - ghcr.io/gsoc2/syft:{{.Tag}}-debug-ppc64le
    goarch: ppc64le
    dockerfile: Dockerfile.debug
    use: buildx
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - gsoc2/syft:debug-s390x
      - gsoc2/syft:{{.Tag}}-debug-s390x
      - ghcr.io/gsoc2/syft:debug-s390x
      - ghcr.io/gsoc2/syft:{{.Tag}}-debug-s390x
    goarch: s390x
    dockerfile: Dockerfile.debug
    use: buildx
    build_flag_templates:
      - "--platform=linux/s390x"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - gsoc2/syft:latest
      - gsoc2/syft:{{.Tag}}
      - ghcr.io/gsoc2/syft:latest
      - ghcr.io/gsoc2/syft:{{.Tag}}
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - gsoc2/syft:{{.Tag}}-arm64v8
      - ghcr.io/gsoc2/syft:{{.Tag}}-arm64v8
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - gsoc2/syft:{{.Tag}}-ppc64le
      - ghcr.io/gsoc2/syft:{{.Tag}}-ppc64le
    goarch: ppc64le
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - gsoc2/syft:{{.Tag}}-s390x
      - ghcr.io/gsoc2/syft:{{.Tag}}-s390x
    goarch: s390x
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/s390x"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

docker_manifests:
  - name_template: gsoc2/syft:latest
    image_templates:
      - gsoc2/syft:{{.Tag}}
      - gsoc2/syft:{{.Tag}}-arm64v8
      - gsoc2/syft:{{.Tag}}-ppc64le
      - gsoc2/syft:{{.Tag}}-s390x

  - name_template: gsoc2/syft:debug
      - gsoc2/syft:{{.Tag}}-debug
      - gsoc2/syft:{{.Tag}}-debug-arm64v8
      - gsoc2/syft:{{.Tag}}-debug-ppc64le
      - gsoc2/syft:{{.Tag}}-debug-s390x

  - name_template: gsoc2/syft:{{.Tag}}
    image_templates:
      - gsoc2/syft:{{.Tag}}
      - gsoc2/syft:{{.Tag}}-arm64v8
      - gsoc2/syft:{{.Tag}}-ppc64le
      - gsoc2/syft:{{.Tag}}-s390x

  - name_template: ghcr.io/gsoc2/syft:latest
    image_templates:
      - ghcr.io/gsoc2/syft:{{.Tag}}
      - ghcr.io/gsoc2/syft:{{.Tag}}-arm64v8
      - ghcr.io/gsoc2/syft:{{.Tag}}-ppc64le
      - ghcr.io/gsoc2/syft:{{.Tag}}-s390x

  - name_template: ghcr.io/gsoc2/syft:debug
    image_templates:
      - ghcr.io/gsoc2/syft:{{.Tag}}-debug
      - ghcr.io/gsoc2/syft:{{.Tag}}-debug-arm64v8
      - ghcr.io/gsoc2/syft:{{.Tag}}-debug-ppc64le
      - ghcr.io/gsoc2/syft:{{.Tag}}-debug-s390x

  - name_template: ghcr.io/gsoc2/syft:{{.Tag}}
    image_templates:
      - ghcr.io/gsoc2/syft:{{.Tag}}
      - ghcr.io/gsoc2/syft:{{.Tag}}-arm64v8
      - ghcr.io/gsoc2/syft:{{.Tag}}-ppc64le
      - ghcr.io/gsoc2/syft:{{.Tag}}-s390x
